=== huynhkimtri/Web-Development-XML/PracXML/web/newXMLDocument.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/newXMLDocument.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE library SYSTEM "newXMLDocument.dtd">

    <library>
    ...
    </library>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT library (book)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT book (title|author|price)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT title (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT author (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT price (#PCDATA)>

=== huynhkimtri/Web-Development-XML/PracXML/web/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE library[
<!ELEMENT library (book)+>
<!ELEMENT book (title+,author,(price|discount))>
<!ELEMENT title (#PCDATA|discount)*>
<!ELEMENT author (#PCDATA)>
<!ELEMENT discount (#PCDATA)>
<!ELEMENT price ANY>
<!ELEMENT p ANY>
<!ATTLIST title bool (aa|cc|ddd) "cc">
]>

<!--<!DOCTYPE library SYSTEM 'newXMLDocument.dtd'>-->
<!--xmlns:a="http://a.com" xmlns:b="http://b.com"-->
<library>
    <book>  
        <title bool="aa"><![CDATA[huyn>?>;;>&apos;hkim tri]]></title>
        <author>t4ri</author>
        <price></price>
    </book>
    <book>
        <title>aaa<discount>asxcxc</discount>
        </title>
        <author>tri</author>
        <price></price>
    </book>
    <book>
        <title>huynhkimtri</title>
        <author>tri</author>
        <price></price>
    </book>
</library>
